// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	int N = 10;
	int swapcnt;
	vector<int> numbers, copied;
	fillvector(numbers, N);
	copied = numbers;
	print(numbers);

	// Insertion Sort
	swapcnt = shellsort(numbers);
	print(numbers);
	cout << "Swap cnt : " << swapcnt << endl;
	for (int i = 0; i < N - 1; i++)
		REQUIRE(numbers[i] <= numbers[i + 1]);
	REQUIRE(swapcnt <= 45);
}
